In [1]:
from sklearn.datasets import load_iris
from sklearn.datasets import load_breast_cancer

# Load the Iris dataset
iris = load_iris()

# Access the data and labels
X = iris.data
y = iris.target
# Load the Breast Cancer dataset
breast_cancer = load_breast_cancer()

# Access the data and labels
X = breast_cancer.data
y = breast_cancer.target



In [2]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Create K = 100 training sets using cross-validation or bagging technique
training_sets = []
for _ in range(100):
    X_train_k, _, y_train_k, _ = train_test_split(X_train, y_train, test_size = 0.2, random_state = 42)
    training_sets.append((X_train_k, y_train_k))

# Build 1 testing set
testing_set = (X_test, y_test)

#Print x_test and y_test
print(X_test)
print(y_test)

[[1.247e+01 1.860e+01 8.109e+01 ... 1.015e-01 3.014e-01 8.750e-02]
 [1.894e+01 2.131e+01 1.236e+02 ... 1.789e-01 2.551e-01 6.589e-02]
 [1.546e+01 1.948e+01 1.017e+02 ... 1.514e-01 2.837e-01 8.019e-02]
 ...
 [1.152e+01 1.493e+01 7.387e+01 ... 9.608e-02 2.664e-01 7.809e-02]
 [1.422e+01 2.785e+01 9.255e+01 ... 8.219e-02 1.890e-01 7.796e-02]
 [2.073e+01 3.112e+01 1.357e+02 ... 1.659e-01 2.868e-01 8.218e-02]]
[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0]


In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Create a list to store the decision trees
decision_trees = []

# Build a Decision Tree for each training set
for X_train_k, y_train_k in training_sets:
    dt = DecisionTreeClassifier()
    dt.fit(X_train_k, y_train_k)
    decision_trees.append(dt)

#Show a decision tree of 1 training set
from sklearn import tree

tree.plot_tree(decision_trees[0])




In [6]:
from sklearn.metrics import accuracy_score
import numpy as np
# Classify data from the testing set using one decision tree
dt_single = decision_trees[0]
y_pred_single = dt_single.predict(testing_set[0])
error_single = 1 - accuracy_score(testing_set[1], y_pred_single)

# Classify data from the testing set using all decision trees
y_pred_all = []
for dt in decision_trees:
    y_pred = dt.predict(testing_set[0])
    y_pred_all.append(y_pred)
y_pred_all = np.array(y_pred_all)
y_pred_majority = np.apply_along_axis(lambda x: np.bincount(x).argmax(), axis = 0, arr = y_pred_all)
error_all = 1 - accuracy_score(testing_set[1], y_pred_majority)

#Show the error rate of the single decision tree and all decision trees
error_single, error_all


(0.07017543859649122, 0.06140350877192979)